- hosts: apache
  become: true
  tasks:
  - name: install apache2
    apt: name=apache2 update_cache=yes state=latest
  - name: Copy your index file
    template:
     src: "index.html"
     dest: "/var/www/html/index.html"
